name: Backend Tests
on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "applications/backend/**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Set working directory
        run: cd applications/backend
      - run: npm install
      - run: npm run lint
